### ISSUE TITLE
enable automated builds

### ISSUE THREAD

**Issue by SingingBush** [dmitry-cherkas/intellij-xslfo-support#6]
register with [travis-ci](https://travis-ci.org) and at the following to a `.travis.yml` file in the root of the project to enable travis builds against multiple versions of intellij:

```yml
language: java

jdk: oraclejdk8

dist: trusty

env:
  global:
  - ORG_GRADLE_PROJECT_downloadIdeaSources=false

jobs:
  include:
    - stage: Build and Test
      env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.2.1
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.2
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.1.5
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.1.4
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.1.3
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.1.2
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.1.1
    - env: ORG_GRADLE_PROJECT_ideaVersion=2017.1
    - stage: Deploy new Release
      script: skip
      env: ORG_GRADLE_PROJECT_ideaVersion=2017.1
      deploy:
        provider: script
        skip_cleanup: true
        script: ./gradlew publishPlugin
        on:
          branch: release
  allow_failures:
    - env: ORG_GRADLE_PROJECT_ideaVersion=LATEST-EAP-SNAPSHOT
```

for the publish plugin to run you'll need to have added the jetbrains repo username & password as environment variables in travis
